version: 1.0
identifier: makfy-ios-build

environment:
  flutter: stable
  xcode: latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

steps:
  - name: Setup Flutter
    run: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter precache --ios
      flutter doctor

  - name: Get Flutter packages
    run: |
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter pub get

  - name: Install CocoaPods
    run: |
      export PATH="$PATH:`pwd`/flutter/bin"
      cd ios
      rm -rf Pods Podfile.lock
      pod install
      cd ..

  - name: Build iOS Release App
    run: |
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter build ios --release --no-codesign
