name: "makfy_new"
description: "this is Makfy App it's application that any one needs to have services."
publish_to: 'none'

version: 1.0.10+19

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  moyasar: ^2.0.13
  google_fonts: ^6.2.1
  board_datetime_picker: ^2.1.4
  flutter_holo_date_picker: ^2.0.0
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  redacted: ^1.0.12
  equatable: ^2.0.5
  fan_carousel_image_slider: ^1.0.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  dropdown_button2: ^2.3.9
  decimal: ^3.0.2
  tabby_flutter_inapp_sdk: ^1.9.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/applogo.png"
