default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight (preview branch)"
  lane :upload_testflight do
    upload_to_testflight(
      ipa: "../build/ios/ipa/new_makfy.ipa", # اسم ملف ipa مبني من المشروع
      skip_waiting_for_build_processing: true
    )
  end

  desc "Release to App Store (main branch)"
  lane :release_to_appstore do
    upload_to_testflight(
      ipa: "../build/ios/ipa/new_makfy.ipa",
      skip_waiting_for_build_processing: false,
      submit_for_review: true,
      reject_if_possible: false,
      automatic_release: false
    )
  end
end
