
default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight (for features branch)"
  lane :upload_testflight do
    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "automatic",
        compileBitcode: true,
        stripSwiftSymbols: true
      },
      xcargs: "-allowProvisioningUpdates",
      output_directory: "../build/ios/ipa",
      output_name: "new_makfy.ipa"
    )

    upload_to_testflight(
      ipa: "../build/ios/ipa/new_makfy.ipa",
      skip_waiting_for_build_processing: true,
      api_key: fetch_appstore_api_key
    )
  end

  desc "Export IPA and release to App Store (main branch)"
  lane :release_to_appstore do
    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "automatic",
        compileBitcode: true,
        stripSwiftSymbols: true
      },
      xcargs: "-allowProvisioningUpdates",
      output_directory: "../build/ios/ipa",
      output_name: "new_makfy.ipa"
    )

    upload_to_testflight(
      ipa: "../build/ios/ipa/new_makfy.ipa",
      skip_waiting_for_build_processing: false,
      submit_for_review: true,
      reject_if_possible: false,
      automatic_release: false,
      api_key: fetch_appstore_api_key
    )
  end
end