name: Build & Upload iOS to TestFlight

on:
  push:
    branches:
      - features

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache iOS
        run: flutter precache --ios

      - name: Build iOS .ipa
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
      - name: R ename IPA to new_makfy.ipa
        run: |
          find build/ios/ipa -name "*.ipa" -exec mv {} build/ios/ipa/new_makfy.ipa \;
      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Upload to TestFlight
        run: fastlane upload_testflight
        working-directory: ios
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
